print('My name is Azamkhodja Akhmedov')
print('I study at WIUT')
print('I learn SWE')
print('I will become the best SWE ever')
print('I want to become a Software Engineer at Google.')
print('I am working on login feature.')